# Generated by Django 4.2 on 2023-04-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVideoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=128)),
                ('user_dyte_participant_id', models.UUIDField(unique=True)),
                ('dyte_meeting_id', models.UUIDField(unique=True)),
                ('support_user_dyte_participant_id', models.UUIDField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DONE', 'Done')], default='PENDING', max_length=10)),
                ('feedback', models.TextField()),
                ('product', models.JSONField()),
                ('support_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
